name: Python CI job

on:
  workflow_call:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs

jobs:
  python-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.9', '3.10' ]
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    # TODO Make this work with poetry
    # TODO Make this an Action
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 bandit pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Tests
      run: pytest

    # TODO Make the config files optional
    - name: Run Linters
      run: |
        BLUE='\033[0;34m'
        NC='\033[0m'
        echo "\n${BLUE}Running Pylint against source and test files...${NC}\n"
        pylint --rcfile=setup.cfg **/*.py
        echo "\n${BLUE}Running Flake8 against source and test files...${NC}\n"
        flake8
        echo "\n${BLUE}Running Bandit against source files...${NC}\n"
        bandit -r --ini setup.cfg
