name: Python CI job

# Inputs:
# - Python version, (Opt., Default '3.10')
# - Dependency manager (PIP/Poetry)
# - Acceptance tests (Boolean)
# - Slack webhook (Opt., Secret)
# - Whether to enforce quality gates, coverage, vulnerabilities, code style...
# - CC, Sonar tokens (Secret)
# - Push destination (Opt., Default to current repo registry)
on:
  workflow_call:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs

# TODO Inputs
jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'  # TODO Parametrize

    - name: Install cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v2.0.1'

    # TODO Make this work with poetry
    # TODO Conditionally decide whether to use PIP or Poetry - https://docs.github.com/en/actions/learn-github-actions/expressions
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 bandit pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # TODO add option for config file
    - name: Run Tests
      run: pytest

    # https://black.readthedocs.io/en/stable/integrations/github_actions.html
    - name: Verify code style (Black)
      uses: psf/black@stable
      with:
        # TODO run `check` only if code style is enforced
        options: "--check --verbose"

    - name: Enforce code style (Flake8)
      run: flake8

    # TODO Make config file optional
    - name: Lint code
      run: pylint --rcfile=setup.cfg **/*.py

    # TODO Make config file optional
    - name: Code security check
      run: bandit -r --ini setup.cfg

    # Run if SONAR_TOKEN (and properties file) is provided
    - name: SonarCloud scanner
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # TODO Run if CC_TEST_REPORTER_ID is provided
    - name: Send report to CodeClimate
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make ci
        prefix: github.com/MartinHeinz/go-github-app
        coverageLocations: |
          ${{github.workspace}}/.coverage:coverage.py

    - id: get-tag
      run: |
        tag=$(echo ${{github.sha}} | cut -c -7)
        echo "::set-output name=tag::$tag"

    - name: Build container image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ghcr.io/${{ github.repository }}
        tags: latest "${{ steps.get-tag.outputs.tag }}"
        containerfiles: |
          ./Dockerfile
        labels: |
          COMMIT=${{ github.event.head_commit.id }}
          COMMIT_MESSAGE=${{ github.event.head_commit.message }}

    # TODO Run conditionally
    - name: Run acceptance tests
      uses: matt-ball/newman-action@master
      with:
        collection: acceptance/collection.json
        environment: acceptance/environment.json

    # TODO - https://github.com/wagoodman/dive
    - name: Analyze image efficiency
      run: echo "Dive"

    - name: Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Push container image
      id: push
      uses: redhat-actions/push-to-registry@v2
      with:
        tags: ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ steps.get-tag.outputs.tag }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml
    - name: Sign the published Docker image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: cosign sign ghcr.io/${{ github.repository }}@${{ steps.push.outputs.digest }}

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Slack notification
      uses: rtCamp/action-slack-notify@v2
      if: always()
      env:
        SLACK_CHANNEL: general
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/${{ github.actor }}.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: Successful build  # TODO Make this conditional
        SLACK_USERNAME: ${{ github.actor }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
